### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by xmha97** [elastic-rock/KeepScreenOn#24] opened 2024-04-03 15:39 UTC
https://github.com/elastic-rock/KeepScreenOn/assets/23485114/278b2888-69e2-4a5b-9def-9f2e34258daa

**Comment by elastic-rock** [comment] 2024-04-03 16:08
This is a duplicate of #11. The problem occurs when a user visits the settings for screen timeout and the timeout is set higher than what MIUI allows (10 minutes). MIUI then sets the timeout to 10 minutes. However, it only happens when you visit the settings and as far as I know only on MIUI. When screen timeout is set to a value MIUI allows (when KeepScreenOn is not enabled), there aren't any problems.

Therefore, the solution is simple. Don't visit the screen timeout settings when KeepScreenOn is enabled. 🙂

**Closed by elastic-rock** 2024-04-03 16:08 UTC

**Comment by xmha97** [comment] 2024-04-03 17:14
Thanks for your explanation, but I found the following app that works without problems:
https://github.com/mueller-ma/Coffee

**Comment by elastic-rock** [comment] 2024-04-03 18:36
The reason Coffee doesn't have the issue is because it uses by default a wake lock instead of changing the settings. KeepScreenOn doesn't use a wake lock but changes the settings instead.

Thank for letting me know.
