### ISSUE TITLE
restore the previous timeout value dosn't work

### ISSUE THREAD

**Issue by islam2hamy** [elastic-rock/KeepScreenOn#11] opened 2023-08-30 12:48 UTC
Hello ,

restore the previous timeout value dosn't work

Steps :
add the app quick settings tile
activet it
deactivet it

the screen timeout dosn't restore the previous timeout value

android : 13
miui : 14.0.12
app v. : 1.5.0

**Comment by elastic-rock** [comment] 2023-09-03 15:28
My first question is, whether the bug occurs in version 1.6.0? If yes, it would be more than ideal but that is rather a hope. :slightly_smiling_face:

If no, I just want to ask you based on what do you assume that the screen timeout is not restored to the previous value? I tried it on MIUI version 14.0.2 (also Android 13) with version 1.5.0 and didn't encounter any issues. :thinking:

**Comment by islam2hamy** [comment] 2023-09-03 18:42
> My first question is, whether the bug occurs in version 1.6.0? 

Yes

> If yes, I just want to ask you based on what do you assume that the screen timeout is not restored to the previous value? I tried it on MIUI version 14.0.2 (also Android 13) with version 1.5.0 and didn't encounter any issues. 🤔

the screen timeout in the phone setting is still 10 m

ps. system language is arabic

**Comment by elastic-rock** [comment] 2023-09-03 19:25
The maximum timeout value in the system settings is 10 minutes on MIUI v14. When I activated the tile and then visited the settings tab where screen timeout can be set, the system set the timeout by itself to 10 minutes, because 10 minutes is the maximum the user can choose from the settings. If one doesn't visit the settings when the tile is active, it works without problems (on my side). I don't know why they do it that way, because on pixel devices, it just shows null and doesn't do stuff you don't want it to do. It may be that you are experiencing this issue. Does the timeout restore correctly, when you don't visit the settings? If you need to, you can check the current timeout using `adb shell settings get system screen_off_timeout`.

**Comment by islam2hamy** [comment] 2023-09-04 01:30
> The maximum timeout value in the system settings is 10 minutes on MIUI v14. When I activated the tile and then visited the settings tab where screen timeout can be set, the system set the timeout by itself to 10 minutes, because 10 minutes is the maximum the user can choose from the settings. If one doesn't visit the settings when the tile is active, it works without problems (on my side). 

yes , and that is fine with me

>I don't know why they do it that way, because on pixel devices, it just shows null and doesn't do stuff you don't want it to do. It may be that you are experiencing this issue. 

yes, but not matter , 10 minutes is ok for me

>Does the timeout restore correctly, when you don't visit the settings? 

deactivate the tile doesn't restore the setting , e.x. 30 second

**Comment by Turhvjbufv** [comment] 2023-10-05 21:19
+1
Deactivating through the quick settings tile also doesn't restore previous value (1m) on s10

**Comment by elastic-rock** [comment] 2023-10-07 06:28
I have pushed out a new update (v1.11.0) which includes a small label inside the app that shows the current screen timeout. Could you please make a screen recording reproducing the bug and returning to the app (to see the label) each time the timeout value supposedly changed? Thank you.

P.S. The update has not yet reached F-Droid but you may get it [from GitHub](https://github.com/elastic-rock/KeepScreenOn/releases/tag/v1.11.0) as the signing keys are the same.

**Comment by islam2hamy** [comment] 2023-10-07 08:00
i have found that , opening the screen timeout in the phone setting mking the tile deactiveted

Steps :
add the app quick settings tile
activet it
open the screen timeout in the phone setting 
Go back tobthe tile

the tile is deactiveted !

**Comment by Turhvjbufv** [comment] 2023-10-07 08:01
New update seems to have fixed the problem, thanks

**Comment by Turhvjbufv** [comment] 2023-10-07 08:02
> I have pushed out a new update (v1.11.0) which includes a small label inside the app that shows the current screen timeout. Could you please make a screen recording reproducing the bug and returning to the app (to see the label) each time the timeout value supposedly changed? Thank you.
> 
> P.S. The update has not yet reached F-Droid but you may get it [from GitHub](https://github.com/elastic-rock/KeepScreenOn/releases/tag/v1.11.0) as the signing keys are the same.

The new update seems to have fixed the problem, but I didn't play much with it since I don't have much time currently

**Comment by elastic-rock** [comment] 2023-10-17 08:06
Any updates on the matter?

**Comment by Turhvjbufv** [comment] 2023-10-17 08:24
For me the new update fixed the problem

**Comment by islam2hamy** [comment] 2023-10-17 08:35
> Any updates on the matter?

For me

> i have found that , opening the screen timeout in the phone setting making the tile deactiveted
Steps :
add the app quick settings tile
activet it
open the screen timeout in the phone setting
Go back to the tile

the tile is deactiveted !

**Comment by elastic-rock** [comment] 2023-10-17 20:14
> > Any updates on the matter?
> 
> For me
> 
> > i have found that , opening the screen timeout in the phone setting making the tile deactiveted
> > Steps :
> > add the app quick settings tile
> > activet it
> > open the screen timeout in the phone setting
> > Go back to the tile
> > the tile is deactiveted !

But otherwise, is it working as expected?

**Comment by islam2hamy** [comment] 2023-10-18 03:06
> > > Any updates on the matter?
> > 
> > 
> > For me
> > > i have found that , opening the screen timeout in the phone setting making the tile deactiveted
> > > Steps :
> > > add the app quick settings tile
> > > activet it
> > > open the screen timeout in the phone setting
> > > Go back to the tile
> > > the tile is deactiveted !
> 
> But otherwise, is it working as expected?

yes

**Comment by elastic-rock** [comment] 2023-10-22 17:35
The fact that opening the settings panel sets the timeout to 10min is a feature of MIUI and not something that can be prevented by the app. Therefore, I am closing this issue as everything else is working as expected. If something doesn't work, I will be happy to help.

**Closed by elastic-rock** 2023-10-22 17:35 UTC
Labels: bug
